### PR TITLE
Added EL Support

### PR DESCRIPTION
**Pull request by akhoury6**
Added a systemd script for EL Linux

### CODE REVIEW

**Comment by retr0h** [comment]
Will verify this in a little while.  You can ignore the travis error.  I no longer use travis in favor of [molecule](https://github.com/metacloud/molecule).  Will re-enable travis once [molecule](https://github.com/metacloud/molecule) supports docker.

**Comment by retr0h** [comment]
etcd is failing to start due to the followings.

* Permissions on the service file should not be executable
* The `BusName` needs to be unique.  The service fails to start as is.

```
Apr 18 02:49:24 localhost systemd: Configuration file /etc/systemd/system/etcd.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

After correcting these locally, the cluster does startup properly.

```
[root@etcd-03 ~]# curl http://172.28.128.5:2379/v2/machines
http://172.28.128.3:2379, http://172.28.128.4:2379, http://172.28.128.5:2379
```

**Comment by akhoury6** [comment]
Good catch.

I opted to switch to `type=notify` and remove `BusName` completely, as to my knowledge etcd does not acquire a name on the D-Bus bus. This was in the output of `service etcd status` before the switch:

```
Apr 18 18:59:05 box20.bnx.dev etcd[24758]: set the cluster version to 2.3 from store
Apr 18 18:59:05 box20.bnx.dev etcd[24758]: starting server... [version: 2.3.1, cluster version: 2.3]
Apr 18 18:59:05 box20.bnx.dev etcd[24758]: failed to notify systemd for readiness: No socket
Apr 18 18:59:05 box20.bnx.dev etcd[24758]: forgot to set Type=notify in systemd service file?
...
```

**Comment by retr0h** [comment]
@akhoury6 looks good.  Thanks!

**Pull request merged**
