### PR TITLE
Switch from custom rsync to synchronize module

### PR DESCRIPTION
**Pull request by retr0h**

### CODE REVIEW

**Comment by zehicle** [comment]
I like #32 approach better than this.  I'd suggest killing this patch and taking #32.  It looks good to me. 

I can test on my local system is that would help.

**Comment by retr0h** [comment]
> I like #32 approach better than #31 (which I wrote). I'd suggest killing #31 and taking this one.
> 
> I can test on my local system is that would help.

You work is still relevant.  The synchronize simply fronts rsync under the hood, and requires rsync be installed regardless.

Thanks for the contribution @zehicle!

**Comment by zehicle** [comment]
cool, I'll merge and update then.

On 06/30/2016 03:52 PM, John Dewey wrote:
>
>     I like #32 <https://github.com/retr0h/ansible-etcd/pull/32>
>     approach better than #31
>     <https://github.com/retr0h/ansible-etcd/pull/31> (which I wrote).
>     I'd suggest killing #31
>     <https://github.com/retr0h/ansible-etcd/pull/31> and taking this one.
>
>     I can test on my local system is that would help.
>
> You work is still relevant. The synchronize simply fronts rsync under
> the hood, and requires rsync be installed regardless.
>
> Thanks for the contribution @zehicle <https://github.com/zehicle>!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/retr0h/ansible-etcd/pull/32#issuecomment-229785267>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAsP1H8pS3Qg04I8NajoUXojtnBxWfvFks5qRCx2gaJpZM4JB6o5>.
>

-- 
  

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by retr0h** [comment]
BTW @zehicle you guys should check out [molecule](https://github.com/metacloud/molecule) to test your ansible roles.

**Comment by zehicle** [comment]
I'll look - we've got Digital Rebar to automate roles pretty easily
against multiple platforms.  I'll pull together my workflow into a video
over next week.

On 06/30/2016 04:37 PM, John Dewey wrote:
>
> BTW @zehicle <https://github.com/zehicle> you guys should check out
> molecule <https://github.com/metacloud/molecule> to test your ansible
> roles.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/retr0h/ansible-etcd/pull/32#issuecomment-229796408>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAsP1BujK94QkPppoxeIU8BcaCQAPa2bks5qRDcigaJpZM4JB6o5>.
>

-- 
  

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Pull request merged**
